language: r
sudo: true

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("ggplot2", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("testthat", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("xml2", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("doParallel", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("NMF", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("igraph", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("knitr", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("XML", repos = "http://cran.rstudio.com")'

r_binary_packages:
  - devtools
  - ggplot2
  - testthat
  - xml2
  - doParallel
  - NMF
  - igraph
  - knitr
  - XML

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - hadley/dplyr
  - hadley/lubridate

notifications:
    email:
      on_success: change
      on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
- LINTR_COMMENT_BOT=false
